### ISSUE TITLE
How to ?

### ISSUE THREAD

**Issue by vgalisson** [judahtanthony/node-aescrypt#1]
Hi, I've come by your repository and I was wondering how can we use your package?

Is it possible to add some explanations in your README.md ?

Thanks in advance ☺️

**Comment by judahtanthony** [comment]
You are absolutely right.  I had wanted to figure out how to take a password through stdin while also piping in content on stdin before I considered this stable and updated the README.  However, that problem seems much more difficult than I had anticipated.  I'll try to update the README to describe the current usecases.

**Comment by vgalisson** [comment]
Thank you very much !
